### ISSUE TITLE
User flash 

### ISSUE THREAD

**Issue by sdmg15** [bpesquet/OC-MicroCMS#6]
Hi, 
I noticed that in nearly all user flashs you have missed writting  `````php  #successfully 
thanks.

**Comment by bpesquet** [comment]
Hi,
Could you elaborate in english or french ? I don't really understand the problem.
Thx.

**Comment by sdmg15** [comment]
Je disais que vous aviez oublier le second «s» dans «successfully»  dans les messages utilisateurs.

**Comment by bpesquet** [comment]
OK, ce sera corrigé prochainement, merci !

**Comment by bpesquet** [comment]
Je préfère laisser l'issue ouverte, ça me rappelle que j'ai qqch à faire ;)

**Comment by bpesquet** [comment]
Done in v2.0
